//
//  Variables.swift
//  PhraseApp
//
//  Created by Drolllted on 19.06.2024.
//

import Foundation


enum Variables: String, CaseIterable {
    case age = "age"
    case alone = "alone"
    case amazing = "amazing"
    case anger = "anger"
    case architecture = "architecture"
    case art = "art"
    case attitude = "attitude"
    case beauty = "beauty"
    case best = "best"
    case birthday = "birthday"
    case business = "business"
    case car = "car"
    case change = "change"
    case communication = "communication"
    case computers = "computers"
    case cool = "cool"
    case courage = "courage"
    case dad = "dad"
    case dating = "dating"
    case death = "death"
    case design = "design"
    case dreams = "dreams"
    case education = "education"
    case environmental = "environmental"
    case equality = "equality"
    case experience = "experience"
    case failure = "failure"
    case faith = "faith"
    case family = "family"
    case famous = "famous"
    case fear = "fear"
    case fitness = "fitness"
    case food = "food"
    case forgiveness = "forgiveness"
    case freedom = "freedom"
    case friendship = "friendship"
    case funny = "funny"
    case future = "future"
    case god = "god"
    case good = "good"
    case government = "government"
    case graduation = "graduation"
    case great = "great"
    case happiness = "happiness"
    case health = "health"
    case history = "history"
    case home = "home"
    case hope = "hope"
    case humor = "humor"
    case imagination = "imagination"
    case inspirational = "inspirational"
    case intelligence = "intelligence"
    case jealousy = "jealousy"
    case knowledge = "knowledge"
    case leadership = "leadership"
    case learning = "learning"
}
